version: '3'
services:
  api:
    build: .
    container_name: nestjs_api
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - JUSTANAME_CHAIN_ID=${JUSTANAME_CHAIN_ID}
      - JUSTANAME_DOMAIN=${JUSTANAME_DOMAIN}
      - JUSTANAME_ORIGIN=${JUSTANAME_ORIGIN}
      - JUSTANAME_API_KEY=${JUSTANAME_API_KEY}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
